export const SAVE_DATA_RED="SAVE_DATA_RED";
export const SAVE_DATA_GREEN="SAVE_DATA_GREEN";
export const SAVE_DATA_BLUE="SAVE_DATA_BLUE";
export const SHOW_PANEL="SHOW_PANEL";
export const CANCLE_PANEL="CANCLE_PANEL";
export const GET_TABLES_RED="GET_TABLES_RED";
export const GET_TABLES_GREEN="GET_TABLES_GREEN";
export const GET_TABLES_BLUE="GET_TABLES_BLUE";
